### ISSUE TITLE
Encountered exception while executing function. Exception = JSRT error 0x30003

### ISSUE THREAD

**Issue by shaunybrown** [syedhassaanahmed/databricks-notebooks#2]
When running the script as is, with correct version of  azure-cosmosdb-spark (uber jar) I get the following error:

`[java.lang.RuntimeException:` com.microsoft.azure.documentdb.DocumentClientException: {"Errors":["Encountered exception while executing function. Exception = JSRT error 0x30003"]}
ActivityId: d7306bea-c6f2-11e8-8193-375e5e99d753, Request URI: /apps/715a7d31-043d-41ec-bd1d-560fc8b975e9/services/0696254c-0f9a-469c-aca9-a8f303497b48/partitions/7e58d373-7496-441d-99cd-b0c1bca2189c/replicas/131826360024207383p//, StatusCode: InternalServerError, SubStatusCode: ]
	at com.microsoft.azure.cosmosdb.spark.CosmosDBSpark$.bulkImport(CosmosDBSpark.scala:311)
	at com.microsoft.azure.cosmosdb.spark.CosmosDBSpark$.savePartition(CosmosDBSpark.scala:467)
	at com.microsoft.azure.cosmosdb.spark.CosmosDBSpark$.com$microsoft$azure$cosmosdb$spark$CosmosDBSpark$$savePartition(CosmosDBSpark.scala:408)
	at com.microsoft.azure.cosmosdb.spark.CosmosDBSpark$$anonfun$1.apply(CosmosDBSpark.scala:192)
	at com.microsoft.azure.cosmosdb.spark.CosmosDBSpark$$anonfun$1.apply(CosmosDBSpark.scala:183)
	at org.apache.spark.rdd.RDD$$anonfun$mapPartitionsWithIndex$1$$anonfun$apply$26.apply(RDD.scala:859)
	at org.apache.spark.rdd.RDD$$anonfun$mapPartitionsWithIndex$1$$anonfun$apply$26.apply(RDD.scala:859)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:42)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:336)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:300)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:87)
	at org.apache.spark.scheduler.Task.run(Task.scala:112)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:384)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

Driver stacktrace:
	at org.apache.spark.scheduler.DAGScheduler.org$apache$spark$scheduler$DAGScheduler$$failJobAndIndependentStages(DAGScheduler.scala:1740)`

**Comment by shaunybrown** [comment]
Similar issue with the python version

`Py4JJavaError                             Traceback (most recent call last)
<command-579638577315327> in <module>()
     10 cosmosDbFormat = "com.microsoft.azure.cosmosdb.spark"
     11 
---> 12 cosmosDbVertices.write.format(cosmosDbFormat).mode("append").options(**cosmosDbConfig).save()
     13 cosmosDbEdges.write.format(cosmosDbFormat).mode("append").options(**cosmosDbConfig).save()

/databricks/spark/python/pyspark/sql/readwriter.py in save(self, path, format, mode, partitionBy, **options)
    703             self.format(format)
    704         if path is None:
--> 705             self._jwrite.save()
    706         else:
    707             self._jwrite.save(path)

/databricks/spark/python/lib/py4j-0.10.6-src.zip/py4j/java_gateway.py in __call__(self, *args)
   1158         answer = self.gateway_client.send_command(command)
   1159         return_value = get_return_value(
-> 1160             answer, self.gateway_client, self.target_id, self.name)
   1161 
   1162         for temp_arg in temp_args:`

**Comment by syedhassaanahmed** [comment]
Hi @shaunybrown After attaching the library to the cluster did you restart the cluster? I've encountered transient errors before if I didn't restart the cluster.

**Comment by shaunybrown** [comment]
I've set up a new cluster and it is working fine on that, looks like my original cluster isn't removing the old uber driver on restart
